.github/workflows/ci.yml, package.json, yarn.lock
fixed #1 
`"name": "vscode_deno"` and `"publisher": "the deno authors"` will cause package error:
> **ERROR**  Invalid extension name 'vscode_deno'
> **ERROR**  Invalid publisher name 'the deno authors'. Expected the identifier of a publisher, not its human-friendly name.  Learn more: https://code.visualstudio.com/api/working-with-extensions/publishing-extension#publishing-extensions
so I disabled the package step
=> use github actions

package.json, yarn.lock
via https://github.com/justjavac/typescript-deno-plugin/commit/41b28727c5f0e2b6fc917315d0b7ce16d0482b5a
--------
How the extension works: If user installs Deno, the lib.deno.d.ts file will be created by `deno types`  when the extension is initialized. If user has not installed Deno, will use the extension bundled lib.deno.d.ts file, which is the latest version.
Another implementation is to download the lib.deno.d.ts file from github. Fortunately, starting from version 0.39.0, Deno's releases assets include the lib.deno.d.ts file.
https://github.com/denoland/vscode_deno/blob/f5d6c124d4dc6e0a0a63eaf918327f78b01063a2/client/src/utils.ts#L238-L239
=> upgrade lib.deno.d.ts to 1.0.0-rc2

scripts/build.sh
vscode marketplace do not display `Release.md` on the right aside, just only `changelog.*`.
=> show changelog on vscode marketplace

client/src/extension.ts, client/src/utils.ts, package.json, package.nls.json
* Added `deno.unstable` as configuration option
* Changed extension name to `deno` and publisher to `denoland`
A user might not want to support unstable Deno features and should have the option to choose if enable unstable type definition
=> Add deno.unstable configuration

client/src/deno.ts, client/src/extension.ts, client/src/utils.ts, package.json, yarn.lock
Use the full path of the deno executable file to run `deno types`... etc.
fixes #19
=> rewrite deno finder

README.md
This pull request changes the incorrect configuration string `deno.enabled` to `deno.enable` in the README.
=> Fix incorrect configuration string in README

client/src/extension.ts
Fix wrong VS Code Extension ID.
Explicitly `await` (and catch) `deno.generateDtsForDeno`, so all definition files are in place, before the extension finishes activation phase.
fixes #74, #66, #62, #48
=> Fix broken installation of TS definition files for `Deno`.

README.md, client/src/extension.ts, package.nls.fr.json, package.nls.it.json, package.nls.json, package.nls.pt-pt.json, package.nls.zh-cn.json
This PR adds a `deno.enablePatterns` config option that lets you specify particular paths or folders where the extension is enabled. This is useful for projects that contain both Node code and Deno code, such as the `vscode_deno` repo itself. This relates to #87 
Example usage:
```json
{
"deno.enablePatterns": ["packages/deno/**", "*.deno.ts"]
}
```
Each item in the array matches a regex and only one item needs to match to enable the extension on that file. 
This is more of a suggestion. Totally understand if this is the wrong naming convention, or the wrong way to go about this. 
I've played around with this in a number of different configurations in [this example repo I setup](https://github.com/Flaque/deno_ext_example). Though it might be a good idea for someone else to play around …
=> Add "enablePatterns" config option

README.md, package.json
Having `deno.enable` default to `true` causes a lot of problems especially in workspaces that are not Deno projects.
Ref https://github.com/denoland/vscode_deno/issues/105
Ref https://github.com/denoland/vscode_deno/issues/89
Ref https://github.com/denoland/vscode_deno/issues/69
=> Change default value of deno.enable to false

.github/workflows/build.yml, .gitignore, README.md, package.json
This might fix publishing in CI. Bumped version to 2.0.15
=> Use npm instead of yarn

core/deno_normalize_import_statement.test.ts, core/deno_normalize_import_statement.ts, core/util.test.ts, core/util.ts
close #138 
Typescript does not add extensions by default for cached modules when import from autocomplete
```diff
- import { foo } from "./bar"
+ import { foo } from "./bar.ts"
```
Now it has been fixed
/cc @ry @bartlomieju 
```
PASS  core/deno_normalize_import_statement.test.ts
PASS  core/deno_deps.test.ts
PASS  core/deno_type_hint.test.ts
PASS  core/cache.test.ts
PASS  core/import_map.test.ts
PASS  core/module_resolver.test.ts
PASS  core/cache_map.test.ts
PASS  core/file_walker.test.ts
PASS  core/extension.test.ts
PASS  core/configuration.test.ts
PASS  core/deno_cache.test.ts
PASS  core/deno.test.ts
PASS  core/util.test.ts
PASS  core/hash_meta.test.ts
------------------------------------|---------|----------|---------|---------|-------------------
File                                | …
```
=> fix: autocomplete supports adding extensions

core/deno_deps.ts
It handles ENOENT error thrown by the getAllDenoCachedDeps function when
the deno/deps directory does not exists (e.g. a deno fresh install).
Fix #158
=> Fix #158 handle properly dependencies cache when deno/deps does not exists

core/deno_cache.ts, core/module_resolver.test.ts, core/module_resolver.ts, core/testdata/deno_dir_manifest/deps/http/localhost_PORT3000/51a61f14fdad404fd2c9187363be7846d6d3b84a2b8697b9bd50c60d4509ab60.metadata.json
Ref. Deno source: https://github.com/denoland/deno/blob/2da084058397efd6f517ba98c9882760ec0a7bd6/cli/disk_cache.rs#L55
Ref. previous PR: https://github.com/justjavac/typescript-deno-plugin/pull/63
This adds support for port numbers in remote module resolution. I didn't see any places that would support a test for this, so please test with a local file server before merging.
I think this should resolve #171.
=> Add support for URLs with non-default ports

core/import_enhanced.test.ts, core/import_enhanced.ts
Add support for
- `export {} from "https://deno.land/..."`
- `export type {} from "https://deno.land/..."`
=> fix: support export syntax in import IntelliSense

.github/workflows/build.yml
This adds the `deno-vscode.vsix` as a release artifact so VS Code based editors that do not have access to the Visual Studio Marketplace (e.g. `theia` and `code-server`) can make use of the extension easily.
Fixes #79
=> build: release vsix

Releases.md, package.json, typescript-deno-plugin/src/plugin.ts
Ref https://github.com/denoland/deno/pull/7800﻿
=> chore: remove importsNotUsedAsValues

package-lock.json, typescript-deno-plugin/src/index.ts
The language server can now provide hover/quick info information and document highlights, so should be suppressed when Deno is enabled on a workspace.
=> feat: add suppressing quick info and document highlights

package-lock.json, package.json, typescript-deno-plugin/src/index.ts
Because it is not currently included, the plugin is not installed in the released VS Code extension, which means double diagnostics.
=> fix: include typescript-deno-plugin in vsix

client/src/commands.ts, client/src/extension.ts, package.json, typescript-deno-plugin/src/index.ts
This PR adds support to allow the Deno LSP to display "reference" code lenses.
Code Lenses are disabled by default for Deno, and for references there are two options to enable them:
- `deno.codeLens.references` - Display code lenses information which allows you to see visually how many references an item has in the code.
- `deno.codeLens.referencesAllFunctions` - Display reference information for all functions (this can get a bit annoying, so this sub option aligns to the vscode built in plugin for TypeScript).
An example of it working in VSCode:
This requires a version of Deno that includes denoland/deno#9316 for it do anything useful.
=> feat: code lens for references

client/src/commands.ts, client/src/extension.ts, client/src/lsp_extensions.ts
Looks like I was a bit premature.  We don't need `deno/applyCodeActionCommand` because we won't be processing any of the the fixes that include the command.  The only command at the moment is to do an npm package install.  It also works asynchronously inside of tsc, which our current integration doesn't support, and so it was easier to remove the functionality from the Deno lsp that make it work and then do nothing.
=> fix: remove deno/applyCodeActionCommand

client/src/commands.ts, client/src/extension.ts, client/src/lsp_extensions.ts
This PR adds support for Deno cache quick fix and a visual status bar indication when caching, as well as provides a window status bar indication of the version of the Deno lsp it is using.
=> feat: support deno cache quick fix

Releases.md, client/src/commands.ts, client/src/constants.ts, client/src/extension.ts, client/src/welcome.ts, media/welcome.css, media/welcome.js, package.json
This adds a welcome screen when installing the extension for the first time and it activating providing information on how to get started with both the extension and Deno:
It can also be display at any time by using the _Deno: Welcome_ command from the command pallette.
=> feat: add a welcome screen for extension

client/src/commands.ts
Instead of previewing the Deno LSP status virtual document as a markdown file, it opens it in markdown preview.  This will allow us to provide a more "readable" version of the status page in the future without having to look directly at markdown.
=> feat: use preview instead of display for status

client/src/extension.ts, package.json
Fixes #334
This PR fixes the extension so it activates on the `deno.welcome` and `deno.initializeWorkspace` commands. It also hides the `deno.cache` and `deno.status` commands until the LSP has been started.
=> chore: activate extension on command

README.md, package.json
=> docs: recommend import_map.json instead of import-map.json

README.md, client/src/extension.ts, package.json
This allows setting a specific path to the `deno` executable for the extension, in either the workspace or globally, instead of being dependent on `deno` being in the environment path only.
=> feat: add deno.path setting

client/src/debug_config_provider.ts, client/src/extension.ts, package.json
This re-adds back support for out of the box debug support, which we had in the 2.X branch.
=> feat: read-add debug support

package.json
These settings will impact the behaviour of completions in future releases of the Deno LSP which align it to the behaviour of the built-in TypeScript/JavaScript extension in VScode.
=> feat: add settings to affect completions

client/src/extension.ts
See issue #361 for more details.
This ensures the `deno` command automatically resolves the same way it resolves on the command line.
=> feat: Manual resolution of `deno` command on Windows

client/src/extension.ts
We needed this because our project has a monorepo, and the deno binary is automatically installed on a folder relative to the workspace
=> Support for relative path resolution (using workspaces) in deno.path

CHANGELOG.md, README.md, client/src/commands.ts, client/src/extension.ts, client/src/interfaces.d.ts, client/src/lsp_extensions.ts, docs/ImportCompletions.md, package.json, schemas/deno-import-intellisense.schema.json, typescript-deno-plugin/src/index.ts
This PR adds the required configuration information to support import registry completions.  For it to work though, it needs a version of the language server the supports the import registry completions (but should not break with versions that don't support it).
=> feat: add support for import registry completions

README.md
There was a broken link (link error), which has been corrected.
=> fix: broken links "Import Completions" in README

client/src/extension.ts, client/src/interfaces.d.ts, client/src/lsp_extensions.ts, client/src/notification_handlers.ts, docs/ImportCompletions.md, package.json, typescript-deno-plugin/src/index.ts
Add the `deno.suggest.imports.autoDiscover` option and responds to `deno/registryState` notifications.
Requires denoland/deno#10813 to do anything useful.
=> feat: support registry auto discovery

client/src/extension.ts
Sets the semver to `>=1.10.3` which includes the ability to format `.md`, where in earlier versions will cause strange diagnostics.
=> fix: bump semver of extension

.github/workflows/ci.yml, .vscodeignore
Fixes #439
Updates the `.vscodeingore` which changed behaviour in the `vsce` tool for packaging extensions as well as pins at a specific version to avoid accidental breaking changes in the future.
=> fix: update packaging and pin vsce version

client/src/util.ts
Closes #451.
The reason this occurs is because the GUI sets the value in the settings json to `"deno.path": ""`
=> fix: setting then clearing "deno.path" config should allow language server to start

README.md, client/src/commands.ts, client/src/constants.ts, client/src/content_provider.ts, client/src/extension.ts, client/src/ts_api.ts, client/src/types.d.ts, client/src/util.ts, package.json
This is essentially #453, but without the `parent-pid` changes.
These changes also...
1. Allow users to update deno then just do the "Restart Language Service" command.
2. Allow users to update "deno.path" and have the changes take effect immediately.
=> fix: better handling when language server fails to start

client/src/commands.ts, client/src/extension.ts, client/src/types.d.ts, package.json, typescript-deno-plugin/src/index.ts
Closes #287 
Provides a `deno.cache` setting which gets passed to the language server (and set as the `DENO_DIR` when running a test) which allows explicitly specifying a cache directory as part of the workspace configuration.
Requires https://github.com/denoland/deno/pull/11527 to do anything interesting.
=> feat: add ability to set cache directory in settings

README.md, client/src/constants.ts
This updates to the min version to >= 1.13.0.  While this isn't technically true, v1.13 and later contains several stability and diagnostic fixes which we want to _nag_ people into having when using the LSP.
=> chore: bump minimum version of Deno CLI

client/src/debug_config_provider.ts, package.json
This deals with two issues that were causing challenges when configuring debug:
- There was a static config in the `package.json` which then causes the debug provider to not actually work.
- The debug provider did not take into account the context, meaning that if you were using an import map, a cache path, or a config file, none of those would be configured to automatically occur when starting debug or generating a `launch.json`.
In addition, the naming of the launch tasks have been adjusted to be better aligned with `Chrome` and `Node.js` debug configurations provided by vscode.
=> fix: debug config provider

README.md, client/src/shared_types.d.ts, package.json
=> feat: support deno.json(c) files

client/src/notification_handlers.ts
=> fix: do not cache unsupported origins in config

client/src/constants.ts
Updating the minimum version of the Deno CLI.  The main reason is that Deno 1.17 ships with support for v2 of the registry suggestions, and we want to roll out a v2 version of the `deno.land/x` and `deno.land/std` registry, which would require Deno 1.17 or later to take full advantage of it.
I don't think we should publish a version of vscode_deno for a week or so, so that people organically upgrade to Deno 1.17 before we start "warning" them.
=> chore: update min version

client/src/shared_types.d.ts, package.json, typescript-deno-plugin/src/index.ts
This PR enables support for TLS certificate related options for registry completions and caching remote dependencies which are being added to CLI.
Ref: denoland/deno#13467
=> feat: support certificate related options

client/src/extension.ts, client/src/shared_types.d.ts
I discovered this when working on the testing API.  Some keys were missing here, which meant that some settings weren't sent during initialisation, meaning they were stuck at their default values, even if they had been modified in the `settings.json` and wouldn't be changed unless the `settings.json` file was edited.
=> fix: send all workspace settings during initialisation

.vscode/launch.json, client/src/constants.ts, client/src/extension.ts, client/src/shared_types.d.ts, client/src/types.d.ts, package-lock.json, package.json, typescript-deno-plugin/package-lock.json, typescript-deno-plugin/package.json, typescript-deno-plugin/src/index.ts
Closes: #633
This PR introduces the `deno.enablePathsOnly` configuration option. When set, vscode_deno will suppress built-in TypeScript/JavaScript language service features for the enabled paths within a workspace folder.  For example, setting `"deno.enablePathsOnly": ["./worker"]` would disable diagnostics and other language service features for any files in the `worker` path of the workspace (or its sub-folders).
This will require a similar feature in the Deno language server to only provide language service features for the enabled paths.
=> feat: support Deno enabling specified workspace paths

client/src/constants.ts, client/src/enable.ts, client/src/extension.ts
This will prompt the user to enable Deno for a workspace or workspace folder when a `deno.json` or `deno.jsonc` is configured in the root of the workspace (or workspace folder):
The prompt will only occur if:
- The extension has activated.
- If a workspace is open.
- The `deno.enable` setting is not explicitly set for the workspace or workspace folder.
- A `deno.json` or `deno.jsonc` is already present in the root or is created while the workspace is open.
When a user selects either _No_ or _Enable_ the value will be set in the workspace settings (or workspace folder settings when using multi-root workspaces) and the user will no longer be prompted (unless the remove the explicit configuration setting).
=> feat: prompt for enabling when config detected

client/src/commands.ts, client/src/extension.ts, client/src/lsp_extensions.ts, client/src/tasks.ts, client/src/types.d.ts
This is the vscode_deno implementation of being able to provide tasks defined in a Deno configuration file:
https://user-images.githubusercontent.com/1282577/160353997-60a72c99-5818-423a-a5b3-c8805ba4f868.mp4
It requires a yet to be raised PR for Deno CLI which provides the `denoConfigTasks` feature.
Ref: denoland/deno#13910
=> feat: support config file tasks

.vscode/launch.json, .vscode/tasks.json, README.md, package.json
Apologies if this breaks any existing workflows.
I'm not sure what setup is currently being used to work on this extension. But `npm run watch` didn't seem to work for me.
Either way, watching seems redundant since the extension host needs to be reloaded and this already makes a build before reloading.
I've also modified the readme, a build step like `npm run compile` is no longer required as the `Launch Client` already runs the build step for you.
I've also answered a few questions I had myself in the readme.
Fixes: #592
=> chore: use esbuild script for vscode tasks

client/src/util.ts
Now this is super easy to do. Should reduce the liklihood of people having issues when it's not on the PATH.
=> fix: resolve deno from the default install location if it's not on the PATH

.vscodeignore
I noticed a demo image isn't excluded from the extension package, hence this pull request. With this change, package size is down from 1.59MB to 390.76KB.
It does not break the links as VSCode rewrites assets in README to use GitHub links.
=> Exclude demo image from extension package

client/src/lsp_extensions.ts, client/src/tasks.ts
The `deno/task` LSP request expects no parameters. Current code displays a "Failed to retrieve config tasks." error message as the request fails every time I launch if `deno.unstable` is true.
=> "Failed to retrieve config tasks."

client/src/extension.ts, client/src/shared_types.d.ts, typescript-deno-plugin/src/index.ts
This fixes an issue where the inlay hint configuration is not available at startup.
=> fix: send inlay hints config on init

typescript-deno-plugin/src/index.ts
Path separators on Windows caused an incorrect behavior in `#fileNameDenoEnabled` that resulted in a non-functioning `deno.enablePaths` setting on Windows. This fixes #668.
=> fix: enablePaths on Windows

client/src/debug_config_provider.ts, client/src/extension.ts
Fixes #774 and possibly makes #608 obsolete.
Please let me know if I should change or test something specific. I've tested with current and old Deno versions.
I had to change the argument received in the constructor because I needed to check the version of the Deno Server.
From what I observed (code below), `getSettings === extensionContext.clientOptions.initializationOptions`, so I adjusted the calls.
https://github.com/denoland/vscode_deno/blob/5ab30d8c7e966add3db6a4ecef1cfccd49cf0d3b/client/src/extension.ts#L198
https://github.com/denoland/vscode_deno/blob/5ab30d8c7e966add3db6a4ecef1cfccd49cf0d3b/client/src/extension.ts#L245
=> feat: make `--inspect-wait` default when debugging

client/src/debug_config_provider.ts
Silences the warning "please use type node instead"
=> Use "node" launch type instead of "pwa-node"

client/src/debug_config_provider.ts
As requested https://github.com/denoland/vscode_deno/pull/775#discussion_r1057971783
=> feat: make `--inspect-brk` default in older versions of Deno

client/src/commands.ts, client/src/extension.ts, client/src/status_bar.ts
This PR adds a click handler to the status bar item which opens the output panel. Noticed that the prettier extension has this too and it's kinda neat from a UX perspective for debugging. Otherwise you'd need to open the output panel manually and pick the appropriate extension from the dropdown menu.
=> feat: show output panel on status bar click

README.md, client/src/extension.ts, client/src/shared_types.d.ts, package.json, typescript-deno-plugin/src/index.ts
This PR added a feature called cache on save that includes:
- A setting entry `deno.cacheOnSave` of type of bool, defaults to `true`
- A listener of `onDidSaveTextDocument` that will call `deno.cache` command if `deno.cacheOnSave` is set to `true`
closes: #826
=> feat: cache on save

client/src/commands.ts, client/src/debug_config_provider.ts, client/src/util.ts
vscode_deno offers a code lens action "Run Test | Debug". However when clicking the "Debug", it triggers a breakpoint which an user did not set.
- Unified the logic for selecting the appropriate debugging flag (`--inspect-brk` or `--inspect-wait`) based on the behavior of pull request #775.
Tested on windows, not sure about other OS but I think there should be no problem.
The breakpoint continues to be triggered only on the first time and not from the second. I'm not sure about underlying cause.
=> feat: allow --inspect-wait when debugging test

client/src/extension.ts
The check added in https://github.com/denoland/vscode_deno/commit/b6a0d19ca12f0439e12d3387de61d7d693431697 will fail to detect 1.37.0 when creating the initialization options, because of course we don't have server version info yet at that point. So we check it again after starting the language server and maybe restart.
Enable for release candidates of 1.37.0 as well.
Also we weren't signalling config changes to the server for `deno.enable` and `deno.enablePaths`.
=> fix: properly detect 1.37.0

typescript-deno-plugin/src/index.ts
Typo fix. I don't know the effect but I guess methods `getCompilerOptionsDiagnostics` and `getNavigateToItems` would have been faulty with `"deno.enable": false`.
=> fix: missing parentheses for Plugin::#denoEnabled() call

README.md, client/src/constants.ts, client/src/enable.ts, client/src/extension.ts, client/src/shared_types.d.ts, client/src/status_bar.ts, client/src/types.d.ts, package.json, typescript-deno-plugin/src/index.ts
Closes #817. Won't work until Deno 1.37 or built with patch https://github.com/denoland/deno/pull/20475.
=> feat: "deno.disablePaths" setting

package.json
This reverts commit d299be89ede2002e43413f493c179eb857391399 (#913).
Assuming no more release till the one with 1.37.
=> Revert "fix: default "deno.enable" to false temporarily (#913)"

client/src/extension.ts, client/src/shared_types.d.ts
Closes #928. Coupled with https://github.com/denoland/deno/pull/20593. Note that `LanguageSettings::preferences` and `LanguageSettings::updateImportsOnFileMove` aren't stored or respected by the LSP yet, just sending them in advance.
=> feat: include "javascript" and "typescript" settings in LSP init options

client/src/commands.ts, client/src/extension.ts, client/src/status_bar.ts, client/src/welcome.ts, package.json
When moving the `deno.cache` command server-side (https://github.com/denoland/deno/pull/20111), it stopped working when you run it from the command palette since no args are passed in that case. I was testing it with the code action only. This separates the one intended to be run that way into a separate command: `deno.client.cacheActiveDocument`. There's no sense in implementing these under the same command.
For clarity and future-compat, this renames all of the commands that are supposed to be implemented by the client/editor from `deno.<name>` to `deno.client.<name>`.
=> fix: regression when caching via the command palette

client/src/extension.ts, typescript-deno-plugin/src/index.ts
https://github.com/denoland/deno/pull/20632 moves `deno.cacheOnSave` handling to the server-side, available as of `1.37.0+33f8432`. Disables the implementation here for LSP versions > 1.37.0 (this leaves a dead-zone where you won't have either for some stale canary versions, but that's okay and we want to ship this to proper nightly users).
=> chore: version check for client-side "deno.cacheOnSave"

client/src/extension.ts, typescript-deno-plugin/src/index.ts
Start sending notebook cells to the LSP.
VSCode stores these cells as documents with URLs like:
```
vscode-notebook-cell:/home/nayeem/projects/vscode_deno/notebook.ipynb#W0aIKpasdpH53D%3D
```
When sending them to the LSP, I've mapped them to:
```
deno-file-fragment:/home/nayeem/projects/vscode_deno/notebook.ipynb#W0aIKpasdpH53D%3D
```
because it's neutral to other editors and because the handling in the LSP is pretty generic wrt 'file fragments'. Neither `file:///` (actual FS files with no fragment) nor `deno:` (static virtual documents with paths not related to the actual FS) are appropriate for this.
=> feat: register notebook cells with the language client

client/src/extension.ts, client/src/fresh/extension.ts, client/src/fresh/generate.ts, client/src/fresh/getRoutes.ts, client/src/fresh/snippets.ts, client/src/fresh/webview.ts, media/fresh/main.css, media/fresh/main.js, media/fresh/vscode.css, package.json
This PR introduces Fresh features:
The Route view is designed as a live documentation, especially for beginners of Fresh.
- Special files like `_app.tsx` are displayed with distinct icons and are accompanied by links to the documentation. This prevents beginners from being confused when they encounter these files right after initializing a project.
- URL Tester for testing dynamic routes.
- Parameters for dynamic routes can be entered directly into a text input, and can be previewed in a browser with the icon on the right.
**Constraints:**
Users need to start the Fresh server before the browser preview. Also, the URL is fixed at http://localhost:8000/.
**Note:**
The Fresh routes view should not appear in non-Fresh projects as it checks `fresh.gen.ts`. I believe I haven't changed the …
=> feat(fresh): add fresh route view, snippets

client/src/commands.ts
There's a big chunk of blocking sync IO we do on the main LSP thread at https://github.com/denoland/deno/blob/v1.37.1/cli/lsp/documents.rs#L1437-L1448. I tried moving it to a blocking thread with a cancellation token triggered on shutdown, but something else was still blocking the shutdown notification from being received.
Either way, It would be good to increase this timeout for projects with large dep graphs like fresh.
cc @marvinhagemeister
=> fix: increase client shutdown timeout from 2s to 10s

client/src/extension.ts, package.json
This will let other editors use it for free. I'll actually add the command on the LSP after this lands (https://github.com/denoland/deno/pull/20823), I want to include the date for this change in a comment there. Backwards-compatible.
=> refactor: move "deno.reloadImportRegistries" command to the server

schemas/lockfile.schema.json
Fixes #960. Also unsupports older versions because it would be very complex and there's no point.
=> chore: update lockfile schema to v3

client/src/extension.ts, client/src/lsp_extensions.ts, client/src/tasks_sidebar.ts
Fixes #963. Coupled with https://github.com/denoland/deno/pull/20827. The tasks sidebar will now only work with Deno 1.37.2 or whichever version that PR lands for, since it depends on the `sourceUri` being included in task definitions.
=> fix: update tasks sidebar on config change notification

client/src/ts_api.ts
Fixes #883.
Fixes #888.
We only access the builtin TS extension to disable its calls. So we shouldn't error loudly if it's not there. In fact, it's advisable to disable that extension in pure Deno workspaces for perf.
=> fix: don't error on missing typescript-language-features

client/src/commands.ts
Fixes #582. Now shows:
```
Deno project initialization failed: Unable to write to Workspace Settings because no workspace is opened. Please open a workspace first and try again.
```
=> fix: show error message for workspace init failure

client/src/extension.ts, client/src/shared_types.d.ts, package.json
- Deprecate our mirrors of built-in settings that we now support under `typescript.*` and `javascript.*`.
- Mark some settings as `resource`-scoped so they can vary between workspace folders. Depends on https://github.com/denoland/deno/pull/20937.
- I realised `deno.codeLens.implementations`, `deno.codeLens.references` and `deno.codeLens.referencesAllFunctions` are also mirrors of built-in settings. Start sending over their original counterparts so we can deprecate those too.
=> chore: deprecate "deno.*" mirror settings

README.md, client/src/extension.ts
I want to get rid of this double server startup ASAP -- it exacerbates https://github.com/denoland/deno/issues/20700 because it leads to an extra background server process that doesn't exit.
=> chore: remove compat paths for lsp < 1.37.0

client/src/tasks_sidebar.ts
=> fix: tasks panel empty on win machines

README.md, client/src/commands.ts, client/src/extension.ts, client/src/shared_types.d.ts, package.json, typescript-deno-plugin/src/index.ts
Coupled with https://github.com/denoland/deno/pull/21482.
=> feat: "deno.internalInspect" setting

client/src/enable.ts, client/src/extension.ts, client/src/shared_types.d.ts, package.json, typescript-deno-plugin/src/index.ts
Towards #908. For the last step we have to wait some more version cycles and then remove this code from the server: https://github.com/denoland/deno/blob/v1.39.4/cli/lsp/config.rs#L793-L795. No changes are required to the compat table since it already excludes whatever version pairs this would affect.
=> chore: default "deno.enablePaths" to null

README.md, client/src/commands.ts, client/src/enable.ts, client/src/extension.ts, client/src/lsp_extensions.ts, client/src/shared_types.d.ts, client/src/status_bar.ts, client/src/types.d.ts, typescript-deno-plugin/src/index.ts
Align enable-checks with how they are done in the server in preparation for multi-deno.json support.
This exposed lots of cruft in the way we were handling workspace settings, e.g. still storing and refreshing per-document settings, our explicit type definitions for them being redundant and other things.
Also remove compat paths for LSP versions <= 1.37.0.
=> refactor: clean up enable settings on plugin interface

client/src/commands.ts, client/src/enable.ts, client/src/extension.ts, client/src/status_bar.ts, client/src/testing.ts, client/src/types.d.ts
This completes the client-side changes for https://github.com/denoland/deno/pull/21029.
Also fixes disposable handling for resources created with the language client. Some were only being disposed when the extension deactivated, now their lifetimes are properly tied to the client. There were no bugs from this as far as I can tell. Just dangling event handlers.
=> feat: accept notifications for subdirectory deno.json files

schemas/lockfile.schema.json
Closes #1037.
Implements the changes to `LockfileContent` in https://github.com/denoland/deno_lockfile/commit/c263e012deac9733c3077ebadf81d0b2647dc204. I'm not confident in figuring out meaningful descriptions so if the field doesn't have a doc comment in rust, it's missing here.
=> feat: add workspace and jsr fields to lockfile schema

client/src/extension.ts
Fixes #1050. I think the issue arose from trying to run the command while the language server was initializing. We'll follow up if not.
=> fix: register commands before starting language server

client/src/extension.ts, package.json
Closes #1058.
Ref #1027.
We're restoring this as an alias of `Deno: Enable` because of documentation in the wild that might refer to this one.
=> feat: restore init workspace command as alias

client/src/commands.ts
Previously, the user was prompted with a few questions about their workspace configuration, making it clear that something was happening. Now that there is no more user input required, it is not clear that the extension is doing anything.
This change-set shows a show a modal info box to the user after the Deno workspace is initialized.
In a future commit, this should be replaced with a message to the status bar.
=> feat: Show a modal dialog after workspace init

README.md, client/src/lsp_extensions.ts, client/src/tasks_sidebar.ts, client/src/types.d.ts
Towards TODO mentioned in https://github.com/denoland/deno/blob/v1.40.2/cli/lsp/mod.rs#L66-L68. This bumps the minimum required CLI version from 1.37.1 to 1.37.2. I also inverted the compat table, since the CLI version is more likely to be fixed for the user.
=> chore: rename "deno/task" request to "deno.taskDefinitions"

package.json
The default value for `Deno.enable` was `null` which is not valid. This commit removes the `null` value and makes the default value `false`.
This change-set also updates the formatting of the `internalInspect`.
=> fix: Explicitly allow null in deno.enable

package.json
the `deno.unstable` flag is only used to control test execution. This change-set updates the description to reflect that.
=> docs: correct the deno.unstable description

client/src/commands.ts
Don't spawn the language server when `deno.enable: false` and `deno.enablePaths: null`, or `deno.enablePaths: []`.
=> fix: don't spawn the language server if explicitly disabled settings

client/src/lsp_extensions.ts, client/src/tasks.ts, client/src/tasks_sidebar.ts
Use the correct workspace folder and `-c subdir/deno.json` when executing subdirectory `deno.json` tasks via the sidebar. Also dedup some code.
=> fix: handle nested config files in tasks sidebar

README.md, client/src/commands.ts, client/src/enable.ts, client/src/extension.ts, client/src/upgrade.ts, package.json
Coupled with https://github.com/denoland/deno/pull/25552. This change would be breaking but it adds a configuration hook which reverts the setting to a boolean for older versions of the CLI/server.
Also removes some old compat paths. Unsupports Deno <= 1.39.4.
=> feat: unstable setting as list

.github/workflows/ci.yml, client/src/commands.ts, client/src/semver.ts, client/src/util.ts
- I tried using deno 1.46.0-rc.0 and https://github.com/denoland/vscode_deno/pull/893 did not worked.
- https://github.com/denoland/vscode_deno/pull/1142 fixes one semver check of two usages.
- Create new semver module for applying `{ includePrerelease: true }` for all `semver.satisfies` usages.
With prerelease deno and windows, click 'Run Test | **Debug**' above Deno.test and see it does not pause at debug session start.
=> feat: use --inspect-wait for prerelease deno

client/src/commands.ts, client/src/enable.ts, client/src/extension.ts, package.json
Related: https://github.com/denoland/deno/issues/25607.
=> feat: helper prompts for tsconfig.json compiler options

schemas/lockfile.schema.json
=> feat: lockfile v4 schema

client/src/constants.ts, package.json
=> feat: "deno.trace.server" setting

client/src/commands.ts
The diagnostics from this setting cannot be suppressed by our plugin: https://github.com/denoland/vscode_deno/issues/437#issuecomment-1720393193. When users see diagnostics from both `ts` and `deno-ts`, this has always been the cause. So disable it for the workspace if it's enabled there or in user settings.
Non-exhaustive list of reports:
https://github.com/denoland/vscode_deno/issues/66#issuecomment-1316154839
#466
https://github.com/denoland/vscode_deno/issues/668#issuecomment-1159481069
#715
#1072
#1098
#1184
#1190
=> feat: disable "enableProjectDiagnostics" on enable

client/package-lock.json, client/package.json, client/src/lsp_extensions.ts, client/src/testing.ts, package-lock.json, package.json, typescript-deno-plugin/package-lock.json, typescript-deno-plugin/package.json
I wanted a Deno testing experience that's closer to Vitest's UI or Wallaby.js. As in
- See the test results inline in the IDE
- Re-run the tests and update the IDE's UI when saving 
This now works 🎉 
https://github.com/user-attachments/assets/b283b1e1-528f-47d5-b436-86c546d0d3c7
(The execution speed is very slow, because I have not compiled Deno in release mode)
To do so, I had to
- Bump the required VSCode version. This lets us take advantage of VSCode's "continuous run".
- Update the LSP to support these features. https://github.com/denoland/deno/pull/27762
- Recreate the TestRun object when the tests are being restarted. This is because VSCode does not support changing the status of a test from failure back to success.
- Learn about a VSCode peculiarity …
=> Run tests with file watcher

README.md
If unchecked, the code lens is not displayed. Version 3.43.5.
https://docs.deno.com/runtime/reference/vscode/#testing-code-lens also doesn't say anything about it being deprecated.
=> docs: `deno.codeLens.test` is not deprecated

client/src/commands.ts
Fixes "Deno Language Server client: couldn't create connection to server. Error: spawn EINVAL" #1257
I've debugged it locally to ensure it works on my Windows PC.
---
`vscode_deno` is currently broken on Win32 VSCode 1.92 (July 2024) and later. `spawn`'s/`spawnSync`'s EINVAL error was introduced in the Node.js 18.x, 20.x, 21.x releases lines to mitigate CVE-2024-27980. The fix was implemented at nodejs/node@69ffc6d50d.
Running a .bat or .cmd via spawn or spawnSync _without assigning the shell option_ is prohibited in VSCode 1.92 and later.
=> fix(client): set `{ shell: true }` in server options for "deno.{bat,cmd}"

client/src/extension.ts, client/src/shared_types.d.ts, client/src/types.d.ts, client/src/util.ts, typescript-deno-plugin/src/index.ts
Go-to definition points to these and they are enabled server-side. Also enable them here so they don't get diagnostics from the built-in TS server.
Related: https://github.com/denoland/deno/issues/27291#issuecomment-2557025337
=> fix: enable paths in the global npm cache

typescript-deno-plugin/src/index.ts
=> fix: handle different drive letters in pathStartsWith()

client/src/commands.ts, client/src/enable.ts
- Reverts #1166
The LSP/CLI can read tsconfigs now.
=> chore: remove tsconfig helper prompt

client/package-lock.json, client/package.json, client/src/testing.ts
This fixes a refreshing bug with upcoming pull-based diagnostics.
This following line hadn't been added in the version we were using: https://github.com/microsoft/vscode-languageserver-node/blob/df56e720c01c6e2d7873733807418f6ce33187ad/client/src/common/diagnostic.ts#L616
=> chore: update vscode-languageclient
