denoland/vscode_deno

client/src/deno.ts
client/src/extension.ts
client/src/utils.ts
package.json
yarn.lock

fixed #8 
available on vscode marketplace: https://marketplace.visualstudio.com/items?itemName=justjavac.vscode-deno

support webworker's .d.ts

---

client/src/extension.ts
package.json
server/package.json
server/src/code_actions.ts
server/src/connection.ts
server/src/project_service.ts
server/src/server.ts
server/src/utils.ts
server/yarn.lock
yarn.lock

without vscode_deno:
with vscode_deno:
fix several issues: 
- https://github.com/justjavac/typescript-deno-plugin/issues/37
- https://github.com/justjavac/vscode-deno/issues/68
- https://github.com/justjavac/vscode-deno/issues/35
- https://github.com/justjavac/vscode-deno/issues/15

feature diagnostics

---

client/src/extension.ts
client/src/utils.ts

highlight Deno's cached files

---

package.json
yarn.lock

fixed #22
by typescript-deno-plugin@1.25.0
- compatible with deno v1.0.0
- fix importmap using local files

fix importmap using local files

---

package.json
yarn.lock

via https://github.com/justjavac/typescript-deno-plugin/commit/2661ebe8c4ee7a6ad219216997c1813815ecfa1a
- fixed #14
- fixed #30

fix intellisense on cached files

---

package.json
yarn.lock

via [typescript-deno-plugin#40](https://github.com/justjavac/typescript-deno-plugin/pull/40)
fixed #27

fix auto import

---

package.json
package.nls.it.json
package.nls.json
package.nls.zh-cn.json

* Added `package.nls.it.json` for italian translation
* Added `deno.command.restartLanguageServer` key

Add Italian translation

---

package.nls.fr.json

- Added `package.nls.fr.json` for French translation containing `deno.command.restartLanguageServer` provided by https://github.com/denoland/vscode_deno/pull/33.

Add French translation

---

package.nls.pt-pt.json

Added package.nls.pt-pt.json for Portuguese translation containing deno.command.restartLanguageServer provided by #33.

Added portuguese translations

---

.github/workflows/ci.yml
package.json

fix extension's name and publisher

---

package.json
yarn.lock

support deno-types

---

package.json
yarn.lock

Just trying to get back to a good state quickly. I don't have time to dig into the extension right now and properly fix it.

revert changes to get it working again

---

.vscode/launch.json
README.md
package.json
package.nls.fr.json
package.nls.it.json
package.nls.json
package.nls.pt-pt.json
package.nls.ru.json
package.nls.zh-cn.json
server/src/connection.ts

fixes #101 
The document/range formatter is now dynamically set with the config option `deno.enableFormatter`.

Made formatter dynamic

---

package.json
typescript-deno-plugin/.npmignore
typescript-deno-plugin/LICENSE
typescript-deno-plugin/package.json
typescript-deno-plugin/src/index.ts
typescript-deno-plugin/src/logger.ts
typescript-deno-plugin/src/plugin.ts
typescript-deno-plugin/tsconfig.json

Fix typescript-deno-plugin

---

core/deno_normalize_import_statement.test.ts
core/deno_normalize_import_statement.ts
typescript-deno-plugin/src/plugin.ts

close #152
before:
after:
PASS  core/hash_meta.test.ts (12.558 s)
PASS  core/deno_cache.test.ts (13.147 s)
PASS  core/module_resolver.test.ts (13.985 s)
PASS  core/import_map.test.ts
PASS  core/configuration.test.ts
PASS  core/deno_type_hint.test.ts
PASS  core/deno_deps.test.ts
PASS  core/util.test.ts
PASS  core/deno_normalize_import_statement.test.ts
PASS  core/file_walker.test.ts
PASS  core/deno.test.ts
PASS  core/extension.test.ts
PASS  core/cache_map.test.ts
PASS  core/cache.test.ts
------------------------------------|---------|----------|---------|---------|-------------------
File                                | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
------------------------------------|---------|----------|---------|---------|-------------------
All files …

fix: fixActions did not import Deno module URL correctly

---

.gitignore
client/src/extension.ts
server/src/deno.ts

In some places ANSI codes where leaking into the UI - that should now stop.

fix: run deno commands with NO_COLOR

---

client/src/extension.ts
client/src/init_project.ts
client/src/mutistep_helper.ts
package.json

Add init project command to quickly get things setup

---

package.json

https://marketplace.visualstudio.com/items?itemName=denoland.vscode-deno-canary

Update version so it can be published on marketplace

---

typescript-deno-plugin/src/index.ts

Because these are becoming available in language server.

feat: suppress references and definitions

---

typescript-deno-plugin/src/index.ts

Ref https://github.com/denoland/deno/pull/8651

chore: disable built in completions

---

client/src/commands.ts
client/src/extension.ts
client/src/lsp_extensions.ts
package-lock.json
package.json

feat: add deno cache command

---

typescript-deno-plugin/src/index.ts

feat: plugin ignores getImplementation requests when Deno enabled

---

typescript-deno-plugin/src/index.ts

Ref https://github.com/denoland/deno/pull/8910﻿

chore: disable built in rename

---

typescript-deno-plugin/src/aspect.ts
typescript-deno-plugin/src/index.ts

We have gotten to the point where we need to disable most of the APIs to built in TypeScript language service when Deno is enabled.

feat: disable most of builtin language service when deno enabled

---

README.md
Releases.md
client/package-lock.json
client/package.json
client/src/commands.ts
client/src/constants.ts
client/src/content_provider.ts
client/src/extension.ts
client/src/initialize_project.ts
client/src/interfaces.d.ts
client/src/lsp_extensions.ts
client/src/multi_step_input.ts
package-lock.json
package.json
typescript-deno-plugin/src/index.ts

This add the initialize workspace command which was simliar to the init command in v2.
It also does additional prep and changes to make this the released branch instead of canary, and updates to vscode-languageserver 7.0 which moves to LSP 3.16 which is what the Deno CLI LSP server is based on.

feat: add initialize workspace command

---

client/package-lock.json
client/package.json
client/src/extension.ts

feat: add version notification message

---

client/src/commands.ts
client/src/constants.ts
client/src/content_provider.ts
client/src/extension.ts
client/src/interfaces.d.ts
package.json

feat: add restart language server command

---

package.json

fix: activate on reloadImportRegistries command

---

docs/ImportCompletions.md

Ref: https://github.com/denoland/vscode_deno/issues/395

docs: remove trailing slash in example

---

client/src/extension.ts
client/src/ts_api.ts
package-lock.json
package.json
typescript-deno-plugin/package-lock.json
typescript-deno-plugin/package.json
typescript-deno-plugin/src/index.ts

fix: properly handle plugin configuration at startup

---

client/src/commands.ts
client/src/extension.ts
client/src/server_info.ts
client/src/shared_types.d.ts
client/src/status_bar.ts
client/src/types.d.ts
typescript-deno-plugin/src/index.ts
typescript-deno-plugin/tsconfig.json

This is based on discussion in #459 and we can probably close that one after this.

feat: hide the status bar unless `deno.enable` is `true`

---

client/package-lock.json
client/package.json
client/src/commands.ts

fix: properly parse config for test code lens

---

package-lock.json
package.json
typescript-deno-plugin/package-lock.json
typescript-deno-plugin/package.json
typescript-deno-plugin/src/index.ts

Trying to fix some minor niggles when supressing diagnostics when Deno is enabled.

fix: better suppression of built in diagnostics

---

client/src/commands.ts

feat: configurable import maps for testing code lens

---

client/src/commands.ts
client/src/types.d.ts

Depends on https://github.com/denoland/deno/pull/13138

feat: support the inspect option for deno.test

---

package.json

fix: update nest.land registry

---

CHANGELOG.md
client/package-lock.json
client/package.json
package-lock.json
package.json
typescript-deno-plugin/package-lock.json
typescript-deno-plugin/package.json

Want to get the update to the nest.land registry out there.

Release 3.10.1

---

typescript-deno-plugin/src/index.ts

fix: utilize fresh arrays when muting built in ls

---

README.md

docs: update README options around testing

---

README.md

https://github.com/denoland/deno/tree/master/docs/contributing - **404**

docs: update contribution guidelines link

---

client/src/commands.ts
client/src/debug_config_provider.ts
client/src/enable.ts
client/src/extension.ts
client/src/tasks.ts
client/src/types.d.ts
client/src/util.ts

fix: do not start lsp or show any messages if Deno not found and not in a Deno project

---

README.md

I have updated the readME involved in #694

Document deno.enable paths in readme.md

---

README.md

#497 vs formatting config

---

README.md

#496 deno cache

---

package.json

feat: enable inlay hints by default

---

package.json
schemas/lockfile.schema.json

This adds support for `deno.lock` with autocomplete and JSON recognition
This also solves #749

Add lockfile schema

---

README.md

ref: https://github.com/badges/shields/issues/8671

fix(README): github workflow status badge

---

package.json

Reverts denoland/vscode_deno#759
Closes https://github.com/denoland/vscode_deno/issues/788

Revert "feat: enable inlay hints by default"

---

README.md
client/src/commands.ts
client/src/debug_config_provider.ts
client/src/extension.ts
client/src/shared_types.d.ts
package.json
typescript-deno-plugin/src/index.ts
typescript-deno-plugin/tsconfig.json

Adds the ability to increase (or decrease) the TypeScript isolate's max memory.

feat: ability to increase typescript isolate's max memory

---

.github/CONTRIBUTING.md
README.md

- Moved contribution documenation to standardized GitHub location
- Linked to new file location
- Rewrote documentation
- Separated content into 3 distinct section ( Prerequisies , Development Setup , Pull Requests )
- Made prerequisites clearer + linked to related project
- Streamlined setup instructions into a list
- Added basic PR instructions + linked to related pages

Improved Contribution Documentation

---

client/src/testing.ts

Fixes #808.
Instead of replacing the whole document, we've been merging the new and old test tree so that dynamically detected steps aren't deleted on each file change. This limits that behaviour to dynamically detected steps. Plus an overall cleanup.

fix: delete renamed test steps

---

client/src/enable.ts
client/src/extension.ts
client/src/shared_types.d.ts
client/src/status_bar.ts
client/src/types.d.ts
package.json
typescript-deno-plugin/src/index.ts

Closes #880.
Needs https://github.com/denoland/deno/pull/20334.

feat: enable via config file detection

---

client/src/extension.ts

For https://github.com/denoland/deno/pull/20111.
Also includes `"enableBuiltinCommands": true` in the server init options. As a temporary restraint to avoid breakage, the LSP will not register built-in commands unless it sees that.

fix: check for existing commands before registering them

---

README.md
client/src/shared_types.d.ts
package.json

feat: remove dead "deno.testing.enable" setting

---

typescript-deno-plugin/src/index.ts

Fixes .. #917 with https://github.com/denoland/deno/pull/20470.

fix: match enablePaths by whole path components

---

client/src/extension.ts
typescript-deno-plugin/src/index.ts

I've written this repeatedly to debug plugin issues etc. Logs like `console.log()`.

chore: improve debug logging util

---

README.md

docs: add troubleshoot for formatter settings

---

client/src/commands.ts

Fixes #944 along with https://github.com/denoland/deno/pull/20697. This will help us debug hanging issues like #943.

fix: append index to status requests

---

client/src/commands.ts
client/src/extension.ts
client/src/server_info.ts
client/src/status_bar.ts
client/src/tasks.ts
client/src/types.d.ts
client/src/upgrade.ts

Coupled with https://github.com/denoland/deno/pull/21105.
https://github.com/denoland/vscode_deno/assets/29990554/05217b2a-6c41-4bd6-a6de-c1f8685b0459

feat: deno upgrade prompt

---

client/src/commands.ts
client/src/extension.ts
package.json

feat: version info command

---

client/src/commands.ts
client/src/extension.ts
package.json

feat: "deno.client.enable" and "deno.client.disable" commands

---

client/src/tasks_sidebar.ts

fix: use "denoTasks" type for task-sidebar commands

---

client/src/commands.ts

fix: check configuration type for deno.json detection

---

schemas/lockfile.schema.json

Mistake from wip code
Fixes #1049.

fix: remove undefined ref in lockfile schema

---

client/src/tasks_sidebar.ts
package.json

Fixes #1079. The menu item was there but it hadn't been implemented.

feat: run task via context menu

---

client/src/enable.ts

fix: sort enable settings by folder

---

client/src/commands.ts
client/src/debug_config_provider.ts
client/src/extension.ts
client/src/upgrade.ts
package.json

If specified it will pass `DENO_FUTURE=1` to the lsp process.

feat: add "deno.future" setting

---

typescript-deno-plugin/src/index.ts

fix: normalize notebook cell filename in plugin

---

client/package-lock.json
client/package.json
client/src/commands.ts
client/src/debug_config_provider.ts
client/src/extension.ts
client/src/upgrade.ts
package.json

Addresses https://github.com/denoland/vscode_deno/issues/837#issuecomment-2204296043. Based on the same `launch.json` keys: https://github.com/Microsoft/vscode/issues/15964.

feat: "deno.env" and "deno.envFile" settings

---

.github/workflows/ci.yml
client/src/commands.ts

fix: use includePrerelease when checking minimum server version

---

.github/workflows/ci.yml

For https://github.com/denoland/vscode_deno/issues/1145

fix: downgrade vsce to 2.31.0

---

client/src/lsp_extensions.ts
client/src/tasks_sidebar.ts
client/src/util.ts

Coupled with https://github.com/denoland/deno/pull/27076. Fixes part of #1211.

fix: support task object notation in sidebar

---

client/src/extension.ts

Fixes #1206. Coupled with https://github.com/denoland/deno/pull/28706.

feat: sync vscode-userdata schemed documents with the lsp

---

schemas/lockfile.schema.json

feat: lockfile v5 schema

---

client/src/tasks_sidebar.ts

fix: empty tasks pane on win machines
